In [1]:
import torch

In [39]:
class TestModel(torch.nn.Module):

    def __init__(self, ip_dims, out_dims):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(ip_dims, 30),
            torch.nn.ReLU(),
            torch.nn.Linear(30, 10),
            torch.nn.ReLU(),
            torch.nn.Linear(10, out_dims),
        )

    def forward(self, ips):
        return self.layers(ips)

In [40]:
ips = torch.rand(1, 10)
ips.shape

torch.Size([1, 10])

In [41]:
test_model = TestModel(10, 3)
test_model

TestModel(
  (layers): Sequential(
    (0): Linear(in_features=10, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=10, bias=True)
    (3): ReLU()
    (4): Linear(in_features=10, out_features=3, bias=True)
  )
)

In [42]:
test_model(ips)

tensor([[-0.2796,  0.0874, -0.1944]], grad_fn=<AddmmBackward0>)

In [48]:
trainable_param_count = 0
for p in test_model.parameters():
    if p.requires_grad == False:
        print(p)
    else:
        trainable_param_count += p.numel()

print(trainable_param_count)

673


In [ ]:
test_model.layers[0].weight.shape # mm 
test_model.layers[0].bias.shape # Add 

torch.Size([30])

In [44]:
torch.nn.Linear(3, 2)(torch.nn.ReLU()(torch.nn.Linear(1, 3)(torch.tensor([[1.]]))))

tensor([[ 0.1447, -0.1717]], grad_fn=<AddmmBackward0>)

In [25]:
torch.tensor([[1.]]).shape

torch.Size([1, 1])

In [26]:
torch.tensor([1.]).shape

torch.Size([1])

In [32]:
x = torch.tensor([3.,], requires_grad=True)
y = x ** 2
y

tensor([9.], grad_fn=<PowBackward0>)

In [33]:
y.backward()

In [34]:
x.grad

tensor([6.])

In [55]:
torch.nn.Linear(1, 1).weight
torch.nn.Linear(1, 1).bias

Parameter containing:
tensor([-0.2237], requires_grad=True)