In [1]:
import torch

In [10]:
class TestModel(torch.nn.Module):

    def __init__(self, ip_dims, out_dims):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(ip_dims, 30),
            torch.nn.ReLU(),
            torch.nn.Linear(30, 10),
            torch.nn.ReLU(),
            torch.nn.Linear(10, out_dims),
        )

    def forward(self, ips):
        return self.layers(ips)

In [11]:
ips = torch.rand(1, 10)
ips.shape

torch.Size([1, 10])

In [12]:
test_model = TestModel(10, 3)
test_model

TestModel(
  (layers): Sequential(
    (0): Linear(in_features=10, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=10, bias=True)
    (3): ReLU()
    (4): Linear(in_features=10, out_features=3, bias=True)
  )
)

In [13]:
test_model(ips)

tensor([[ 0.0438, -0.0986, -0.0690]], grad_fn=<AddmmBackward0>)

In [24]:
torch.nn.Linear(3, 2)(torch.nn.ReLU()(torch.nn.Linear(1, 3)(torch.tensor([[1.]]))))

tensor([[-0.1971,  0.7570]], grad_fn=<AddmmBackward0>)

In [25]:
torch.tensor([[1.]]).shape

torch.Size([1, 1])

In [26]:
torch.tensor([1.]).shape

torch.Size([1])

In [32]:
x = torch.tensor([3.,], requires_grad=True)
y = x ** 2
y

tensor([9.], grad_fn=<PowBackward0>)

In [33]:
y.backward()

In [34]:
x.grad

tensor([6.])