In [ ]:
import torch

In [127]:
torch.manual_seed(22)

input_tokens = torch.tensor([3, 4, 2, 1])
# input_tokens = torch.tensor([0])
print(input_tokens.shape, input_tokens)

vocab_size = max(input_tokens) + 1

embedding_layer = torch.nn.Embedding(vocab_size, 2)
linear = torch.nn.Linear(vocab_size, 2, bias=False)

torch.Size([4]) tensor([3, 4, 2, 1])


In [128]:
one_hot = torch.nn.functional.one_hot(input_tokens)
one_hot

tensor([[0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0]])

In [129]:

linear.weight = torch.nn.Parameter(embedding_layer.weight.T)

In [130]:
embedding_layer.weight

Parameter containing:
tensor([[ 1.0302, -0.5073],
        [-0.1017,  1.3587],
        [-3.0745, -0.7659],
        [ 0.7240,  0.2416],
        [-1.5601,  1.3164]], requires_grad=True)

In [131]:
linear.weight

Parameter containing:
tensor([[ 1.0302, -0.1017, -3.0745,  0.7240, -1.5601],
        [-0.5073,  1.3587, -0.7659,  0.2416,  1.3164]], requires_grad=True)

In [132]:
embedding_layer(input_tokens)

tensor([[ 0.7240,  0.2416],
        [-1.5601,  1.3164],
        [-3.0745, -0.7659],
        [-0.1017,  1.3587]], grad_fn=<EmbeddingBackward0>)

In [133]:
linear(one_hot.float())

tensor([[ 0.7240,  0.2416],
        [-1.5601,  1.3164],
        [-3.0745, -0.7659],
        [-0.1017,  1.3587]], grad_fn=<MmBackward0>)

In [134]:
# embedding_layer(input_tokens)
embedding_layer(torch.tensor([0]))

tensor([[ 1.0302, -0.5073]], grad_fn=<EmbeddingBackward0>)

In [ ]:
ips = torch.tensor([98, 99, 100])
torch.nn.Embedding(3, 2)(ips)